notifications:
  email: false

git:
  depth: 3

language: php
sudo: false

php:
  - 7.2
  - 7.1

env:
  - DB=mysql

matrix:
  fast_finish: true

before_script:
  - composer install
  - npm install

script:
  - ./node_modules/.bin/jshint assets/js/{core,components}
  - ./vendor/bin/phpunit -c tests/units.$DB.xml
  - ./vendor/bin/phpunit tests/configtest
